# $ ansible-vault view secret.yml
# username: user1
# pwhash: f$56fd$pJl4

---
- name: create user accounts for all our servers
  hosts: all
  become: True
  remote_user: devops
  vars_files:
    - secret.yml
  tasks:
    - name: Creating user from secret.yml
      user:
        name: "{{ username }}"
        password: "{{ pwhash }}"
