---
- name: Restart HTTPD if Postfix is Running
  hosts: all
  tasks:
    - name: Get Postfix server status
      command: /usr/bin/systemctl is-active postfix 1
      ignore_errors: yes2  # S’il n’est pas exécuté et que la commande échoue, n’arrêtez pas le traitement
      register: result3

    - name: Restart Apache HTTPD based on Postfix status
      service:
        name: httpd
        state: restarted
      when: result.rc == 04  # 	
Évalue le résultat de la tâche Postfix. Si le code de sortie de la commande systemctl est 0, le service Postfix est actif et cette tâche redémarre le service httpd.
