---
- name: Rechercher des fichiers
  hosts: XXXXXX
  become: yes
  gather_facts: no

  tasks:
  - name: Recherche de la chaine CHAINE_XXXX
    find:
      paths: /
      file_type: file
      patterns: "*CHAINE_XXXX*"
      recurse: yes
    register: result

  - name: Création du log de résultat
    file:
        path: /tmp/XXXXX_{{ inventory_hostname }}.log
        state: touch
        owner: root
        group: root
        mode: '0644'
        force: yes
    delegate_to: localhost

  - local_action:
      module: copy
      content: "{{ result | to_nice_yaml }}"
      dest: /tmp/XXXXX_{{ inventory_hostname }}.log
